apiVersion: v1
kind: Service
metadata:
  name: {{ include "hello-app.fullname" . }}-service
  namespace: {{ include "hello-app.namespace" . }}
  labels:
    {{- include "hello-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
  selector:
    {{- include "hello-app.selectorLabels" . | nindent 4 }}
